
/*------------------------------------------------------------------------
    File        : RTFPart
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : CurtisJA
    Created     : Tue Jul 07 16:04:35 EDT 2020
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface RTFWriter.IDocumentPart:  
  method public char Output().
end interface.